export const REGISTER = "REGISTER";

export const RECEIVED_PRODUCTS = "RECEIVED_PRODUCTS";

export const PRODUCTS_CATEGORIES = "PRODUCTS_CATEGORIES";

export const LOG_IN = "LOG_IN";
export const LOG_USER = "LOG_USER"

export const SEARCH_PRODUCTS = "SEARCH_PRODUCTS";
